<a href="https://colab.research.google.com/github/Ajaykumar-02/Machine-Learning-Algorithms-Projects/blob/main/RandomSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [121]:
df = sns.load_dataset("iris")

In [122]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [123]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
X = df.drop('species', axis=1)
y = df['species']

In [126]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [127]:
from sklearn.neighbors import KNeighborsClassifier

In [128]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [129]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [130]:
model_knn.score(X_test, y_test)

1.0

In [131]:
from sklearn.svm import SVC

In [132]:
model_svm = SVC(gamma='auto')

In [133]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [134]:
model_svm.score(X_test, y_test)

1.0

In [135]:
# now lets use the Random search CV

In [136]:
from sklearn.model_selection import RandomizedSearchCV

In [137]:
# We Use SVM Model

In [138]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter=5,cv=5,return_train_score=False)

In [139]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [140]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00473428, 0.00819216, 0.00558887, 0.00564179, 0.00446639]),
 'std_fit_time': array([0.00057804, 0.00310028, 0.00163614, 0.00179177, 0.0003849 ]),
 'mean_score_time': array([0.00313654, 0.0072258 , 0.00363011, 0.00330224, 0.00392232]),
 'std_score_time': array([0.00016888, 0.00224267, 0.0002636 , 0.00028247, 0.00117802]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'rbf', 'linear'],
              mask=[False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 1, 1, 20, 30],
              mask=[False, False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'linear', 'C': 30}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.96666667, 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03651484, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5], dtype=int32)}

In [141]:
results = pd.DataFrame(classifier_r.cv_results_)

In [142]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004734,0.000578,0.003137,0.000169,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.008192,0.003100,0.007226,0.002243,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005589,0.001636,0.003630,0.000264,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.005642,0.001792,0.003302,0.000282,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,4
4,0.004466,0.000385,0.003922,0.001178,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5

In [143]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1        1       linear         0.980000
2        1          rbf         0.980000
3       20          rbf         0.966667
4       30       linear         0.960000

In [144]:
# We use KNN Model

In [145]:
classifier_2r = RandomizedSearchCV((model_knn),{
    'n_neighbors':[3,5,7,9,11],
     'weights':['uniform','distance'],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],

},n_iter=10,cv = 5, return_train_score=False)

In [146]:
classifier_2r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [3, 5, 7, 9, 11],
                                        'weights': ['uniform', 'distance']})

In [147]:
classifier_2r.cv_results_

{'mean_fit_time': array([0.00459228, 0.00363445, 0.00378299, 0.00479136, 0.0037662 ,
        0.00700645, 0.00349278, 0.00426083, 0.00541596, 0.00372643]),
 'std_fit_time': array([0.00221817, 0.00049376, 0.00041986, 0.00117924, 0.00026156,
        0.00370826, 0.00017259, 0.00100124, 0.00260291, 0.00013722]),
 'mean_score_time': array([0.00457292, 0.00399475, 0.00643525, 0.00649633, 0.00613995,
        0.00799818, 0.00501099, 0.00432119, 0.00563965, 0.00407653]),
 'std_score_time': array([0.00069889, 0.00040198, 0.00100664, 0.0015143 , 0.00141673,
        0.00430058, 0.00020166, 0.00051805, 0.00176094, 0.00014671]),
 'param_weights': masked_array(data=['distance', 'distance', 'uniform', 'uniform',
                    'uniform', 'uniform', 'uniform', 'distance',
                    'distance', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 3, 11, 9, 9, 11, 7, 11, 5, 3],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_algorithm': masked_array(data=['ball_tree', 'auto', 'brute', 'kd_tree', 'ball_tree',
                    'ball_tree', 'brute', 'auto', 'ball_tree', 'kd_tree'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'weights': 'distance',
   'n_neighbors': 3,
   'algorithm': 'ball_tree'},
  {'weights': 'distance', 'n_neighbors': 3, 'algorithm': 'auto'},
  {'weights': 'uniform', 'n_neighbors': 11, 'algorithm': 'brute'},
  {'weights': 'uniform', 'n_neighbors': 9, 'algorithm': 'kd_tree'},
  {'weights': 'uniform', 'n_neighbors': 9, 'algorithm': 'ball_tree'},
  {'weights': 'uniform', 'n_neighbors': 11, 'algorithm': 'ball_tree'},
  {'weights': 'uniform', 'n_neighbors': 7, 'algorithm': 'brute'},
  {'weights': 'distance', 'n_neighbors': 11, 'algorithm': 'auto'},
  {'weights': 'distance', 'n_neighbors': 5, 'algorithm': 'ball_tree'},
  {'weights': 'distance', 'n_neighbors': 3, 'algorithm': 'kd_tree'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.96666667]),
 'split2_test_score': array([0.93333333, 0.93333333, 1.        , 0.96666667, 0.96666667,
        1.        , 0.96666667, 1.        , 0.9       , 0.93333333]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.96666667, 0.98      , 0.97333333, 0.97333333,
        0.98      , 0.98      , 0.98666667, 0.96666667, 0.96666667]),
 'std_test_score': array([0.02108185, 0.02108185, 0.02666667, 0.02494438, 0.02494438,
        0.02666667, 0.01632993, 0.01632993, 0.03651484, 0.02108185]),
 'rank_test_score': array([7, 7, 2, 5, 5, 2, 2, 1, 7, 7], dtype=int32)}

In [148]:
results_knn = pd.DataFrame(classifier_2r.cv_results_)

In [149]:
results_knn.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_n_neighbors,param_algorithm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004592,0.002218,0.004573,0.000699,distance,3,ball_tree,"{'weights': 'distance', 'n_neighbors': 3, 'alg...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,7
1,0.003634,0.000494,0.003995,0.000402,distance,3,auto,"{'weights': 'distance', 'n_neighbors': 3, 'alg...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,7
2,0.003783,0.000420,0.006435,0.001007,uniform,11,brute,"{'weights': 'uniform', 'n_neighbors': 11, 'alg...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,2
3,0.004791,0.001179,0.006496,0.001514,uniform,9,kd_tree,"{'weights': 'uniform', 'n_neighbors': 9, 'algo...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,5
4,0.003766,0.000262,0.006140,0.001417,uniform,9,ball_tree,"{'weights': 'uniform', 'n_neighbors': 9, 'algo...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,5

In [150]:
results_knn[['param_weights','param_n_neighbors','param_algorithm','mean_test_score']]

  param_weights  param_n_neighbors param_algorithm  mean_test_score
0      distance                  3       ball_tree         0.966667
1      distance                  3            auto         0.966667
2       uniform                 11           brute         0.980000
3       uniform                  9         kd_tree         0.973333
4       uniform                  9       ball_tree         0.973333
5       uniform                 11       ball_tree         0.980000
6       uniform                  7           brute         0.980000
7      distance                 11            auto         0.986667
8      distance                  5       ball_tree         0.966667
9      distance                  3         kd_tree         0.966667