<a href="https://colab.research.google.com/github/Ajaykumar-02/Machine-Learning-Algorithms-Projects/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [61]:
df = sns.load_dataset("iris")

In [62]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [63]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
X = df.drop('species', axis=1)
y = df['species']

In [66]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [67]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [69]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [70]:
model_knn.score(X_test, y_test)

1.0

In [71]:
from sklearn.svm import SVC

In [81]:
model_svm = SVC(gamma='auto')

In [82]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [83]:
model_svm.score(X_test, y_test)

1.0

In [79]:
# now lets use the grid search CV

In [80]:
from sklearn.model_selection import GridSearchCV

In [91]:
# We Use SVM Model

In [85]:
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [86]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [87]:
classifier.cv_results_

{'mean_fit_time': array([0.0056066 , 0.00385303, 0.00442281, 0.00377378, 0.00385861,
        0.00368004, 0.00388494, 0.00563407]),
 'std_fit_time': array([1.74986325e-03, 7.16620415e-05, 7.38809262e-04, 1.21399650e-04,
        1.31214929e-04, 1.13991949e-04, 3.18885704e-04, 2.34764576e-03]),
 'mean_score_time': array([0.00326152, 0.00300226, 0.00334444, 0.00289526, 0.00289488,
        0.00339856, 0.00265503, 0.00431738]),
 'std_score_time': array([3.21689890e-04, 3.69746389e-04, 9.60146656e-04, 4.94134455e-05,
        2.42319289e-04, 1.09577012e-03, 2.25407487e-04, 1.66069551e-03]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [88]:
results = pd.DataFrame(classifier.cv_results_)

In [89]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005607,0.001750,0.003262,0.000322,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003853,0.000072,0.003002,0.000370,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004423,0.000739,0.003344,0.000960,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003774,0.000121,0.002895,0.000049,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003859,0.000131,0.002895,0.000242,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003680,0.000114,0.003399,0.001096,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003885,0.000319,0.002655,0.000225,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.005634,0.002348,0.004317,0.001661,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [90]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [92]:
# We use KNN Model

In [97]:
classifier_2 = GridSearchCV((model_knn),{
    'n_neighbors':[3,5,7,9,11],
     'weights':['uniform','distance'],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],

},cv = 5, return_train_score=False)

In [98]:
classifier_2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']})

In [99]:
classifier_2.cv_results_

{'mean_fit_time': array([0.00431256, 0.00420208, 0.0035759 , 0.00414753, 0.00393672,
        0.00479007, 0.00357251, 0.00386624, 0.00356827, 0.00399966,
        0.00354872, 0.00390329, 0.00395389, 0.00448656, 0.00347362,
        0.00409937, 0.00390682, 0.00376668, 0.00368304, 0.00327144,
        0.00343924, 0.00363579, 0.00353045, 0.00363631, 0.00352764,
        0.00568695, 0.00331445, 0.00355883, 0.00343962, 0.00384965,
        0.00332255, 0.00322704, 0.00314198, 0.00347414, 0.00320172,
        0.00302734, 0.00314317, 0.00305905, 0.00308442, 0.00311832]),
 'std_fit_time': array([7.59502798e-04, 1.22620429e-03, 1.19854573e-04, 1.25020520e-03,
        7.93797871e-04, 1.05558050e-03, 2.70144322e-04, 2.67430557e-04,
        1.62492545e-04, 9.31437164e-04, 1.78571957e-04, 3.88317386e-04,
        5.17639656e-04, 1.68737864e-03, 2.44178806e-05, 6.68487823e-04,
        1.40322943e-04, 7.50790062e-05, 4.45976604e-04, 6.46529645e-05,
        4.47099348e-04, 2.33385491e-04, 1.12864585e-04, 4.00376013e-04,
        1.30607343e-04, 4.09751505e-03, 7.30670135e-05, 7.55523461e-05,
        1.41404642e-04, 5.33338898e-05, 1.72630159e-04, 1.00238656e-04,
        4.36355765e-05, 3.63755019e-04, 2.05719896e-04, 1.77388717e-04,
        2.12769666e-04, 1.01052426e-04, 1.77642290e-04, 7.15105359e-05]),
 'mean_score_time': array([0.00586529, 0.00431776, 0.00509987, 0.00393291, 0.00621095,
        0.00571332, 0.00496531, 0.00445418, 0.00502596, 0.00379567,
        0.00504684, 0.00494323, 0.00517387, 0.00386701, 0.00678506,
        0.00500941, 0.00581827, 0.00413504, 0.00492282, 0.00374451,
        0.00463929, 0.00382891, 0.00565047, 0.00391526, 0.00565805,
        0.00496254, 0.00476499, 0.00386872, 0.00483131, 0.00432234,
        0.02248912, 0.00364795, 0.00514789, 0.00374107, 0.00448494,
        0.00341992, 0.00457454, 0.00356402, 0.00453157, 0.0036377 ]),
 'std_score_time': array([8.04721151e-04, 6.04697503e-04, 2.17031719e-04, 5.84022162e-05,
        2.68821713e-03, 2.49322626e-03, 8.11591692e-05, 9.56295909e-04,
        2.49046894e-05, 1.75224090e-04, 1.51387425e-04, 1.92256665e-03,
        1.38042949e-04, 6.33069527e-05, 3.57919287e-03, 1.45638285e-03,
        7.64896618e-04, 1.10827214e-04, 4.48005916e-04, 1.56495355e-04,
        2.25547030e-04, 4.42423176e-05, 1.63089039e-03, 1.05760224e-04,
        1.03584166e-03, 1.49073392e-03, 1.14475722e-04, 4.55302337e-05,
        2.14016076e-04, 1.27767126e-04, 3.43461926e-02, 1.26611589e-04,
        1.09616701e-03, 2.68213819e-04, 1.68221189e-04, 1.28385728e-04,
        1.32986712e-04, 1.02975035e-04, 2.01197787e-04, 7.92094698e-05]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 7, 7, 9, 9, 11, 11, 3, 3, 5, 5, 7, 7, 9, 9,
                    11, 11, 3, 3, 5, 5, 7, 7, 9, 9, 11, 11, 3, 3, 5, 5, 7,
                    7, 9, 9, 11, 11],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 11, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.96666667, 0.97333333, 0.96666667, 0.98      ,
        0.98      , 0.97333333, 0.97333333, 0.98      , 0.98666667,
        0.96666667, 0.96666667, 0.97333333, 0.96666667, 0.98      ,
        0.98      , 0.97333333, 0.97333333, 0.98      , 0.98666667,
        0.96666667, 0.96666667, 0.97333333, 0.96666667, 0.98      ,
        0.98      , 0.97333333, 0.97333333, 0.98      , 0.98666667,
        0.96666667, 0.96666667, 0.97333333, 0.96666667, 0.98      ,
        0.98      , 0.98      , 0.97333333, 0.98      , 0.98666667]),
 'std_test_score': array([0.02108185, 0.02108185, 0.02494438, 0.03651484, 0.01632993,
        0.01632993, 0.02494438, 0.02494438, 0.02666667, 0.01632993,
        0.02108185, 0.02108185, 0.02494438, 0.03651484, 0.01632993,
        0.01632993, 0.02494438, 0.02494438, 0.02666667, 0.01632993,
        0.02108185, 0.02108185, 0.02494438, 0.03651484, 0.01632993,
        0.01632993, 0.02494438, 0.02494438, 0.02666667, 0.01632993,
        0.02108185, 0.02108185, 0.02494438, 0.03651484, 0.01632993,
        0.01632993, 0.01632993, 0.02494438, 0.02666667, 0.01632993]),
 'rank_test_score': array([29, 29, 18, 29,  5,  5, 18, 18,  5,  1, 29, 29, 18, 29,  5,  5, 18,
        18,  5,  1, 29, 29, 18, 29,  5,  5, 18, 18,  5,  1, 29, 29, 18, 29,
         5,  5,  5, 18,  5,  1], dtype=int32)}

In [102]:
results_knn = pd.DataFrame(classifier_2.cv_results_)

In [104]:
results_knn.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004313,0.000760,0.005865,0.000805,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,29
1,0.004202,0.001226,0.004318,0.000605,auto,3,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,29
2,0.003576,0.000120,0.005100,0.000217,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,18
3,0.004148,0.001250,0.003933,0.000058,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,29
4,0.003937,0.000794,0.006211,0.002688,auto,7,uniform,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,5

In [106]:
results_knn[['param_weights','param_n_neighbors','param_algorithm','mean_test_score']]

   param_weights  param_n_neighbors param_algorithm  mean_test_score
0        uniform                  3            auto         0.966667
1       distance                  3            auto         0.966667
2        uniform                  5            auto         0.973333
3       distance                  5            auto         0.966667
4        uniform                  7            auto         0.980000
5       distance                  7            auto         0.980000
6        uniform                  9            auto         0.973333
7       distance                  9            auto         0.973333
8        uniform                 11            auto         0.980000
9       distance                 11            auto         0.986667
10       uniform                  3       ball_tree         0.966667
11      distance                  3       ball_tree         0.966667
12       uniform                  5       ball_tree         0.973333
13      distance                  5       ball_tree         0.966667
14       uniform                  7       ball_tree         0.980000
15      distance                  7       ball_tree         0.980000
16       uniform                  9       ball_tree         0.973333
17      distance                  9       ball_tree         0.973333
18       uniform                 11       ball_tree         0.980000
19      distance                 11       ball_tree         0.986667
20       uniform                  3         kd_tree         0.966667
21      distance                  3         kd_tree         0.966667
22       uniform                  5         kd_tree         0.973333
23      distance                  5         kd_tree         0.966667
24       uniform                  7         kd_tree         0.980000
25      distance                  7         kd_tree         0.980000
26       uniform                  9         kd_tree         0.973333
27      distance                  9         kd_tree         0.973333
28       uniform                 11         kd_tree         0.980000
29      distance                 11         kd_tree         0.986667
30       uniform                  3           brute         0.966667
31      distance                  3           brute         0.966667
32       uniform                  5           brute         0.973333
33      distance                  5           brute         0.966667
34       uniform                  7           brute         0.980000
35      distance                  7           brute         0.980000
36       uniform                  9           brute         0.980000
37      distance                  9           brute         0.973333
38       uniform                 11           brute         0.980000
39      distance                 11           brute         0.986667